clean:
	rm -rf *.mw icc_* *.log zic.timing legalizer_debug_plots net.acts results/* reports/* design_data/ORCA.def
clean_temp:
	rm -rf icc_* *.log *_map* *.txt zic.timing net.acts
run:
	icc_shell -f run.tcl