clean:
	rm -rf *.mw icc_* *.log zic.timing legalizer_debug_plots net.acts results/* reports/* design_data/ORCA.def risc8_port_map* set_pad_attributes_on_cell_risc8.tcl ./.__tmp_pns_undo_file.tcl pna_output
clean_temp:
	rm -rf icc_* *.log *_map* *.txt zic.timing net.acts
run:
	icc_shell -f run.tcl